name: check-new-report
on:
  schedule:
    - cron: '0 13 * * *'
jobs:
  check-new-report:
    name: check-new-report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          cd frontend
          yarn install
          yarn run check-new-report
