name: deploy
on: [push]
jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          cd frontend
          yarn install
          yarn run build
          yarn run deploy
