name: deploy
on: [push]
jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-latest
    container:
      image: lexifdev/circleci-python3-node-gcloud
    steps:
      - uses: actions/checkout@v1
      - run: |
          cd frontend
          yarn install
          yarn run build
          yarn run deploy
